services:
  - type: web
    name: github-oauth-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: GITHUB_CLIENT_ID
        value: your_github_client_id
      - key: GITHUB_CLIENT_SECRET
        value: your_github_client_secret
      - key: SESSION_SECRET
        value: your_session_secret
      - key: CALLBACK_URL
        value: https://github-oauth-backend.onrender.com/auth/github/callback
